In [6]:
# import 
import os 
import geopandas as gpd

In [8]:
# read aoi
aoi_path = '../data/aoi.gpkg'
aoi_gdf = gpd.read_file(aoi_path)

display(aoi_gdf)

,GID_2,GID_0,COUNTRY,GID_1,NAME_1,NL_NAME_1,NAME_2,VARNAME_2,NL_NAME_2,TYPE_2,ENGTYPE_2,CC_2,HASC_2,geometry
0,CIV.3.2_1,CIV,Côte d'Ivoire,CIV.3_1,Comoé,NA,Sud Comoé,NA,NA,Région,Region,NA,CI.CM.SC,"MULTIPOLYGON (((-3.19764 5.10958, -3.19764 5.1..."
1,CIV.6.2_1,CIV,Côte d'Ivoire,CIV.6_1,Lacs,NA,Iffou,NA,NA,Région,Region,NA,CI.LA.IF,"MULTIPOLYGON (((-3.63409 7.05135, -3.63669 7.0..."
2,CIV.6.4_1,CIV,Côte d'Ivoire,CIV.6_1,Lacs,NA,N'zi,NA,NA,Région,Region,NA,CI.LA.NZ,"MULTIPOLYGON (((-4.83022 6.87091, -4.82498 6.8..."

In [9]:
# keep cols
keep_cols = ['COUNTRY', 'NAME_1', 'NAME_2', 'geometry']
aoi_gdf = aoi_gdf[keep_cols]
aoi_gdf = aoi_gdf.rename(columns={
    'COUNTRY': 'Pays',
    'NAME_1': 'District',
    'NAME_2': 'Region'
})

display(aoi_gdf)

,Pays,District,Region,geometry
0,Côte d'Ivoire,Comoé,Sud Comoé,"MULTIPOLYGON (((-3.19764 5.10958, -3.19764 5.1..."
1,Côte d'Ivoire,Lacs,Iffou,"MULTIPOLYGON (((-3.63409 7.05135, -3.63669 7.0..."
2,Côte d'Ivoire,Lacs,N'zi,"MULTIPOLYGON (((-4.83022 6.87091, -4.82498 6.8..."

In [10]:
# save
aoi_gdf.to_file('../data/aoi_clean.gpkg')