In [24]:
# import 
import os 
import geopandas as gpd 
from random import random
import numpy as np

In [ ]:
# processing
# output file 
output_file = '../data/alerts.gpkg'
if not os.path.exists(output_file): 
    # alerts gdf
    alerts_gdf = gpd.read_file('../data/Data.zip')
    alerts_gdf = alerts_gdf.rename(columns={
        'count': 'id', 
        'REGION': 'region',
        'SUPERFICIE': 'superficie_ha',
        'PROBABILIT': 'probabilite'
    })
    alerts_gdf = alerts_gdf[['id', 'region', 'superficie_ha', 'probabilite', 'geometry']]
    display(alerts_gdf)

    # stats
    alerts_gdf['superficie_ha'] = alerts_gdf['superficie_ha']/10_000
    alerts_gdf['probabilite'] = np.random.uniform(0, 100, size=len(alerts_gdf))
    alerts_gdf['probabilite'] = alerts_gdf['probabilite'].apply(lambda x: round(x, 2))
    alerts_gdf['risk'] = np.where(alerts_gdf['probabilite'] > 70, 'High', 'Low')
    display(alerts_gdf)

    # keep cols
    keep_cols = ['id', 'region', 'superficie_ha', 'probabilite', 'risk', 'geometry']
    alerts_gdf = alerts_gdf[keep_cols]

    # save
    alerts_gdf.to_file(output_file)

else : 
    alerts_gdf = gpd.read_file(output_file)
    display(alerts_gdf)

,id,region,superficie_ha,probabilite,geometry
0,584,NaN,58400.0,NaN,"MULTIPOLYGON (((-4.91352 6.65572, -4.91325 6.6..."
1,539,N ZI,53900.0,NaN,"POLYGON ((-4.82321 6.66303, -4.82303 6.66303, ..."
2,619,N ZI,61900.0,NaN,"POLYGON ((-4.74048 6.63973, -4.74174 6.63972, ..."
3,529,N ZI,52900.0,NaN,"MULTIPOLYGON (((-4.73748 6.61098, -4.73748 6.6..."
4,607,N ZI,60700.0,NaN,"MULTIPOLYGON (((-4.72925 7.11076, -4.72898 7.1..."
...,...,...,...,...,...
1722,538,SUD COMOE,53800.0,NaN,"POLYGON ((-2.7595 5.48246, -2.7595 5.48228, -2..."
1723,565,SUD COMOE,56500.0,NaN,"POLYGON ((-2.75926 5.16474, -2.75926 5.16502, ..."
1724,590,SUD COMOE,59000.0,NaN,"MULTIPOLYGON (((-2.75799 5.18329, -2.75799 5.1..."
1725,508,SUD COMOE,50800.0,NaN,"POLYGON ((-2.75448 5.15597, -2.75448 5.15778, ..."
1726,583,SUD COMOE,58300.0,NaN,"MULTIPOLYGON (((-2.74627 5.38077, -2.74627 5.3..."

,id,region,superficie_ha,probabilite,geometry,risk
0,584,NaN,5.84,26.18,"MULTIPOLYGON (((-4.91352 6.65572, -4.91325 6.6...",Low
1,539,N ZI,5.39,99.76,"POLYGON ((-4.82321 6.66303, -4.82303 6.66303, ...",High
2,619,N ZI,6.19,77.80,"POLYGON ((-4.74048 6.63973, -4.74174 6.63972, ...",High
3,529,N ZI,5.29,69.81,"MULTIPOLYGON (((-4.73748 6.61098, -4.73748 6.6...",Low
4,607,N ZI,6.07,46.96,"MULTIPOLYGON (((-4.72925 7.11076, -4.72898 7.1...",Low
...,...,...,...,...,...,...
1722,538,SUD COMOE,5.38,75.76,"POLYGON ((-2.7595 5.48246, -2.7595 5.48228, -2...",High
1723,565,SUD COMOE,5.65,20.23,"POLYGON ((-2.75926 5.16474, -2.75926 5.16502, ...",Low
1724,590,SUD COMOE,5.90,55.24,"MULTIPOLYGON (((-2.75799 5.18329, -2.75799 5.1...",Low
1725,508,SUD COMOE,5.08,69.31,"POLYGON ((-2.75448 5.15597, -2.75448 5.15778, ...",Low
1726,583,SUD COMOE,5.83,13.00,"MULTIPOLYGON (((-2.74627 5.38077, -2.74627 5.3...",Low

In [26]:
region_summary = alerts_gdf.groupby('region')['risk'].agg(
    total_sites='count',
    high_risk_count=lambda x: (x == 'High').sum()
).reset_index()

display(region_summary)

      region  total_sites  high_risk_count
0      IFFOU          647              196
1       N ZI          308              108
2  SUD COMOE          748              252